Repository MYPLACE-team/MYPLACE-Backend, pull requests merged in 2024-02, with the labels that each got.

#16 Feat#9 구글 소셜로그인 API
  config/response.status.js
  src/controllers/auth.controller.js
  src/dtos/auth.dto.js
  src/models/auth.dao.js
  src/models/auth.sql.js
  src/routes/auth.route.js
  src/services/auth.service.js
Labels: FEAT ✨

#24 Feat#23 아카이브 글 삭제
  src/controllers/archive.controller.js
  src/models/archive.dao.js
  src/models/archive.sql.js
  src/routes/archive.route.js
  src/services/archive.service.js
Labels: FEAT ✨

#26 Feat#25 아카이브 글 수정
  src/controllers/archive.controller.js
  src/models/archive.dao.js
  src/models/archive.sql.js
  src/routes/archive.route.js
Labels: FEAT ✨

#28 Feat#27 아카이브 글 상세보기
  src/controllers/archive.controller.js
  src/dtos/archive.dto.js
  src/models/archive.dao.js
  src/models/archive.sql.js
  src/models/place.sql.js
  src/routes/archive.route.js
Labels: FEAT ✨

#31 Feat#18 S3연동 및 JWT 미들웨어로 변경
  config/db.config.js
  config/response.status.js
  package-lock.json
  package.json
  src/controllers/auth.controller.js
  src/middlewares/aws.middleware.js
  src/middlewares/jwt.middleware.js
  src/routes/auth.route.js
  src/services/auth.service.js
  yarn.lock
Labels: FEAT ✨

#36 Feat#35 PM2 추가 및 ES6 구동을 위한 파일 추가
  ecosystem.config.js
  package-lock.json
  package.json
  server.register.js
  yarn.lock
Labels: FEAT ✨

#33 Feat#32 관심 장소 방문 여부 Toggle 기능 추가 및 일부 오류 수정
  config/response.status.js
  src/controllers/place.controller.js
  src/dtos/place.dto.js
  src/models/place.dao.js
  src/models/place.sql.js
  src/routes/place.route.js
  src/services/place.service.js
Labels: FIX 🚑, FEAT ✨

#34 Feat#21 마플 장소등록 수정
  src/controllers/place.controller.js
  src/models/place.dao.js
  src/models/place.sql.js
  src/services/place.service.js
Labels: FIX 🚑

#40 Feat#39 마플 장소 상세 조회
  src/controllers/place.controller.js
  src/dtos/place.dto.js
  src/models/place.dao.js
  src/models/place.sql.js
  src/routes/place.route.js
  src/services/place.service.js
Labels: FEAT ✨

#46 Feat#42 폴더 생성
  src/controllers/archive.controller.js
  src/dtos/archive.dto.js
  src/models/archive.dao.js
  src/models/archive.sql.js
  src/models/user.sql.js
  src/routes/archive.route.js
  src/services/archive.service.js
  yarn.lock
Labels: FEAT ✨

#38 Feat#37 회원정보 조회
  config/response.status.js
  index.js
  src/controllers/auth.controller.js
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/models/user.dao.js
  src/models/user.sql.js
  src/providers/user.provider.js
  src/routes/user.route.js
Labels: FEAT ✨

#44 Feat#43 아카이브 유저/폴더
  src/controllers/archive.controller.js
  src/dtos/archive.dto.js
  src/models/archive.dao.js
  src/models/archive.sql.js
  src/routes/archive.route.js
  src/services/archive.service.js
Labels: FEAT ✨

#64 #30 Feat: 유저 정보 수정기능 및 코드 정리
  config/response.status.js
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/models/user.dao.js
  src/models/user.sql.js
  src/providers/user.provider.js
  src/routes/user.route.js
  src/services/user.service.js
Labels: FEAT ✨

#70 Feat#60 아카이브 리스트 조회 API
  config/response.status.js
  src/controllers/archive.controller.js
  src/dtos/archive.dto.js
  src/models/archive.dao.js
  src/models/archive.sql.js
  src/routes/archive.route.js
  src/services/archive.service.js
Labels: FEAT ✨

#68 #66 Feat: hashtags 추가 및 category->categoryId
  src/dtos/archive.dto.js
  src/models/archive.dao.js
  src/models/archive.sql.js
Labels: FEAT ✨

#75 Feat#74 관심장소 조회에 방문 여부 데이터 추가
  src/dtos/archive.dto.js
  src/dtos/place.dto.js
  src/models/place.sql.js
Labels: FEAT ✨

#84 #83 Fix: 아카이브 작성/수정 데이터타입 수정
  src/models/archive.dao.js
  src/models/archive.sql.js
Labels: FIX 🚑

#92 #91 Fix: 회원정보 수정 응답DTO수정
  config/response.status.js
  src/controllers/user.controller.js
Labels: FIX 🚑
